version: '2'
services:
  jacobryanmedia-services:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn JacobRyanMedia.wsgi:application --bind 0.0.0.0:8000 --workers 4 --thread 8 --timeout=3600
    expose:
      - "8000"
    environment:
      DEBUG: 'true'
    ports:
      - "8000:8000"
    volumes:
      - ./:/JacobRyanMedia
