# Generated by Django 5.0.4 on 2024-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('auth', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('identity', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('media_file', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(default='2024-04-11 21:58:10.251345')),
                ('updated_at', models.DateTimeField(default='2024-04-11 21:58:10.251590')),
            ],
            options={
                'db_table': 'excerpt',
            },
        ),
    ]
