# Generated by Django 5.0.4 on 2024-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='created_at',
            field=models.DateTimeField(default='2024-04-11 22:00:59.761832'),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='updated_at',
            field=models.DateTimeField(default='2024-04-11 22:00:59.762060'),
        ),
    ]
